server:
  port: 8089
spring:
  application:
    name: myspace-gateway
  cloud:
    gateway:
      routes:
        - id: blog
          uri: lb://myspace-blog-management
          predicates:
            - Path=/blog/**
feign:
  hystrix:
    enabled: false

logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG